name: simple_theme_switcher_example
description: An example app demonstrating simple_theme_switcher.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_theme_switcher:
    path: ../ # Use relative path for local testing
